### ISSUE TITLE
Database of given gifts isn't rebuilt from gifted items

### ISSUE THREAD

**Issue by LachlanRidley** [JoXW100/GiftTasteHelper#5]
After the last update, I entirely deleted my GiftTasteHelper folder (not realising that the database files are stored in there). This meant that the mod lost track of all the gifts I'd given. By the looks of it, the problem is that the database is built up as each gift is given, however, I don't see any reason that the database couldn't be regenerated from save data.

**Comment by LachlanRidley** [comment]
@JoXW100 I've had a go at fixing this (first time modding Stardew so apologies for any amateur mistakes).

**Comment by JoXW100** [comment]
This issue has been fixed in version 1.1.0
